#!/usr/bin/env python3
"""
AI-OS Memory Consolidation (deterministic part of the DOC-MEM-002 cycle).

Two actions, both idempotent:

1. Rotate: fully completed day sections of Change_Log_day.md older than
   --days (default 14) move into Knowledge_Base/change_log_archive/YYYY-MM.md.
   This is the Recall -> Archival tier transition: the active log stays small
   (recent context), history stays retrievable. A day is rotated only if
   every entry in it has "Status: done" — days with open work are kept.

2. Index: rebuilds Knowledge_Base/archival_index.md — a navigable index of
   the Archival tier (path, size, first heading) so a model or human can
   locate archived knowledge without loading it all.

Dry-run by default; pass --apply to write changes. Stdlib-only.

Usage:
  python3 Knowledge_Base/consolidate_memory.py             # dry run
  python3 Knowledge_Base/consolidate_memory.py --apply
  python3 Knowledge_Base/consolidate_memory.py --days 30 --apply
"""
import argparse
import os
import re
from datetime import date, datetime

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
LOG = os.path.join(ROOT, "Change_Log_day.md")
ARCHIVE_DIR = os.path.join(ROOT, "Knowledge_Base", "change_log_archive")
INDEX = os.path.join(ROOT, "Knowledge_Base", "archival_index.md")
KB = os.path.join(ROOT, "Knowledge_Base")


def split_days(text):
    """-> (header_before_first_day, [(date_str, section_text)])."""
    parts = re.split(r"(?m)^## (\d{4}-\d{2}-\d{2})\s*$", text)
    head, days = parts[0], []
    for i in range(1, len(parts), 2):
        days.append((parts[i], parts[i + 1]))
    return head, days


def day_completed(section):
    statuses = re.findall(r"(?m)^- Status:\s*(\S+)", section)
    return bool(statuses) and all(s == "done" for s in statuses)


def rotate(days_keep, apply):
    with open(LOG, encoding="utf-8") as fh:
        text = fh.read()
    head, days = split_days(text)
    today = date.today()
    keep, move = [], []
    for d, section in days:
        age = (today - datetime.strptime(d, "%Y-%m-%d").date()).days
        if age > days_keep and day_completed(section):
            move.append((d, section))
        else:
            keep.append((d, section))

    if not move:
        print(f"Rotate: nothing to move (threshold {days_keep} days, "
              f"{len(days)} day section(s) in the active log).")
        return

    for d, section in move:
        month_file = os.path.join(ARCHIVE_DIR, d[:7] + ".md")
        print(f"Rotate: {d} -> {os.path.relpath(month_file, ROOT)}"
              + ("" if apply else "  [dry-run]"))
        if apply:
            os.makedirs(ARCHIVE_DIR, exist_ok=True)
            new = not os.path.exists(month_file)
            with open(month_file, "a", encoding="utf-8") as fh:
                if new:
                    fh.write(f"# Change Log Archive — {d[:7]}\n\n"
                             "(Rotated from Change_Log_day.md by "
                             "consolidate_memory.py; Archival tier per DOC-MEM-002.)\n")
                fh.write(f"\n## {d}\n{section.rstrip()}\n")

    if apply:
        rebuilt = head + "".join(f"## {d}\n{s}" for d, s in keep)
        with open(LOG, "w", encoding="utf-8") as fh:
            fh.write(rebuilt)
        print(f"Active log now holds {len(keep)} day section(s); "
              f"{len(move)} rotated.")


def first_heading(path):
    try:
        with open(path, encoding="utf-8", errors="replace") as fh:
            for line in fh:
                if line.startswith("#"):
                    return line.lstrip("# ").strip()[:80]
    except OSError:
        pass
    return "—"


def build_index(apply):
    rows = []
    for dp, dn, fn in os.walk(KB):
        dn[:] = [d for d in dn if not d.startswith(".") and d != "Repository"]
        for f in sorted(fn):
            if f == "archival_index.md":
                continue
            p = os.path.join(dp, f)
            rel = os.path.relpath(p, ROOT).replace(os.sep, "/")
            size = os.path.getsize(p)
            head = first_heading(p) if f.endswith(".md") else "(non-markdown asset)"
            rows.append(f"| {rel} | {size:,} | {head} |")

    content = (
        "# Archival Memory Index\n\n"
        "(Generated by `consolidate_memory.py` — do not edit by hand. "
        "Archival tier per DOC-MEM-002; regenerate after adding or rotating content.)\n\n"
        f"Generated: {date.today().isoformat()} — {len(rows)} item(s)\n\n"
        "| Path | Bytes | First heading |\n| ---- | ----- | ------------- |\n"
        + "\n".join(rows) + "\n"
    )
    print(f"Index: {len(rows)} item(s)" + ("" if apply else "  [dry-run]"))
    if apply:
        with open(INDEX, "w", encoding="utf-8") as fh:
            fh.write(content)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--days", type=int, default=14,
                    help="rotate completed day sections older than this many days")
    ap.add_argument("--apply", action="store_true", help="write changes (default: dry run)")
    args = ap.parse_args()
    rotate(args.days, args.apply)
    build_index(args.apply)
    if not args.apply:
        print("(dry run — re-run with --apply to write)")


if __name__ == "__main__":
    main()
